### ISSUE TITLE
consul_key data source option for noisy key misses

### ISSUE THREAD

**Issue by mattlqx** [hashicorp/terraform-provider-consul#14]
### Terraform Version
0.9.8

### Affected Resource(s)
- consul_key data source

### Terraform Configuration Files
```hcl
data "consul_keys" "vpc" {
  key {
    name = "vpc_id"
    path = "tf/outputs/vpc_id"
  }
}
```

### Actual Behavior
If `tf/outputs/vpc_id` doesn't exist in Consul, the default behavior is to have an empty string within the data source at the expected `data.consul_keys.vpc.var.vpc_id` location. This type of behavior may be desired in some circumstances, but in others it'd be desired to have the key in Consul be a hard dependency (which may be populated through some mechanism other than Terraform).

It would be nice if there were a `required` option or something else that will cause the Terraform run to fail if the key is not found within Consul. It would also expose Consul or other upstream misconfigurations rather than silently returning empty strings.

**Comment by natefaerber** [comment]
Hi, I totally understand what you mean but I think the purpose of `default` is to give you a way to safely check the result without failing the whole TF run.  Use `default` to set a "MISSING" string and check that later in your TF resources.  You could also do interesting things like set count on a resource to `${signum(length(data.consul_keys.vpc.var.vpc_id))}` to enable/disable a resource if the key in Consul is empty.

It wouldn't be hard to add this behavior and I would be happy to work on it but I'd want to hear from the Hashicorp folks first if this is a behavior that fits into the overall best practices.  But if you find an example where they do this already in a similar data source, I could use that as justification for this work.

**Comment by pearkes** [comment]
I think the best practice here is actually to fail for a data_source. Changing that won't be easy based on current usage. It is possible we could set the behavior via some boolean as discussed with `required` but I think that goes against best practices in a different way.
