### ISSUE TITLE
acl policy and token keep being re-created

### ISSUE THREAD

**Issue by tmdNinja** [hashicorp/terraform-provider-consul#186]
Hi, 

I've been using TF to create consul ACL policy and tokens.
I have set the token property in the provider.

I am experiencing consistency issues.
When i run TF for the first time, it creates the policy and token. 
I can validate it when I ssh into the consul server and with using the master token I can see the newly added policy and token.

When I run apply again TF wants to create the token and policy again.
as if they don't exist.

When I try to view the state file, I can see the policy and token.

More weird then that, after i run apply multiple times I get that there are no changes at all. 
or sometimes the token exist but the policy don't.

Can you maybe shed some light on this issue.

Terraform 0.12.19
Consul provider 2.6.0
### Affected Resource(s)
Please list the resources as a list, for example:
- consul_acl_token
- consul_acl_token

### Expected Behavior
Once the resource created, to not change. 
### Actual Behavior
TF wants to re-create it as if it doesn't exist.

**Comment by remilapeyre** [comment]
Hi @tmdNinja, can you try with the version 2.6.1 ? We fixed a bug related to the ACL in this one: https://github.com/terraform-providers/terraform-provider-consul/commit/39aba055fead64532d954ad9d57555c71cb25cf4.

If the problem persists, can you make sure that the token Terraform is using to connect to Consul has permissions to see both the policy and the token?

**Comment by tmdNinja** [comment]
@remilapeyre thanks for the quick response.
Yes I will try to upgrade to 2.6.1
This problem happened even when I used the master token.

**Comment by tmdNinja** [comment]
@remilapeyre 
when upgraded to 2.6.1 I get this error:
Error: Failed to read policy 'b1afe14d-533f-224d-bfac-6c611b918347': Get http://localhost:28555/v1/acl/policy/b1afe14d-533f-224d-bfac-6c611b918347?dc=prod: dial tcp [::1]:28555: connect: connection refused

I'm using a tunnel from my pc at port 28555 to consul at 8500.
also when I copied the request
to the browser - I got 403
once I added ?token=<master_token> I get the following 
**No path to datacenter**

**Comment by remilapeyre** [comment]
What is the response of `curl -H 'X-Consul-Token: <master-token>' http://localhost:28555/v1/acl/policy/b1afe14d-533f-224d-bfac-6c611b918347?dc=prod`?

**Comment by tmdNinja** [comment]
@remilapeyre as it should.
I get the policy.

I cant explain why this has happened.
Today after that glitche happened it worked fine.
seems that the upgrade to 2.6.1 really did the trick.

**Comment by remilapeyre** [comment]
Do you have a multi-center deployment and if not are you sure all your servers are in the `prod` datacenter? Have you set the `datacenters` attribute on the `consul_acl_policy`?

If it happens again let me know, I will try to reproduce the issue with your configuration.

**Comment by ferrarimarco** [comment]
@remilapeyre I have the very same issue. I have only one datacenter. Setting it in `consul_acl_policy` doesn't make any difference. Thanks!

**Comment by ferrarimarco** [comment]
If I curl it, I get:

```shell
HTTP/2 200
content-type: application/json
vary: Accept-Encoding
x-consul-index: 368871
x-consul-knownleader: true
x-consul-lastcontact: 0
date: Wed, 07 Oct 2020 09:12:05 GMT
content-length: 328
alt-svc: clear
```

and the policy JSON description.

**Comment by ferrarimarco** [comment]
In my case, upgrading to terraform 0.13.4 solved this issue.

**Comment by remilapeyre** [comment]
Do you have an example of Terraform configuration that I can use to reproduce the issue?

**Comment by ferrarimarco** [comment]
I don't have access to that environment anymore. Feel free to close, or keep open as reference :)
