### ISSUE TITLE
CONSUL_HTTP_SSL environment variable not recognised?

### ISSUE THREAD

**Issue by transferkraM** [hashicorp/terraform-provider-consul#215]
Hi there,

it seems the consul resource provider does not recognise CONSUL_HTTP_SSL environment variable.

Related issue from terraform: https://github.com/hashicorp/terraform/issues/23688
Initially I thought this was about terraform but it seems it's about the consul provider.

To be fully compatible with Ansible (consul_kv lookup plugin) I have to use the following environment variables:

```bash
env|grep -v TOKEN|grep CONSUL
```

```
CONSUL_HTTP_SSL=true
CONSUL_HTTP_ADDR=consul.example.com:443
```

### Terraform Version

```
Terraform v0.13.0
```

### Affected Resource(s)

- consul_keys
- anything from the consul provider, I guess

### Terraform Configuration Files

```hcl
terraform {
  backend "consul" {
    address = "consul.example.com"
    scheme  = "https"
    path    = "tfstate/terraform-provider-consul"
  }
}
```

* `terraform init` successful

```hcl
terraform {
  backend "consul" {
    address = "consul.bws.tmnet.zone"
    scheme  = "https"
    path    = "_tfstate/terraform-provider-consul"
  }
}

data consul_keys "consuldata" {
  key {
    name    = "foo"
    path    = "foo/bar"
    default = "bar"
  }
}
```

* `terraform init` successful

```bash
terraform -v
```

```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/consul v2.9.0
```

* Now terraform starts to fail

```bash
terraform plan
```

```
data.consul_keys.consuldata: Refreshing state...

Error: Failed to get datacenter from Consul agent: Unexpected response code: 400 (Client sent an HTTP request to an HTTPS server.
)

  on terraform.tf line 9, in data "consul_keys" "consuldata":
   9: data consul_keys "consuldata" {
```

```hcl
terraform {
  backend "consul" {
    address = "consul.example.com"
    scheme  = "https"
    path    = "_tfstate/terraform-provider-consul"
  }
}

provider "consul" {
  scheme = "https"
}

data consul_keys "consuldata" {
  key {
    name    = "foo"
    path    = "foo/bar"
    default = "bar"
  }
}
```

Adding consul provider configuration with `scheme = "https"` fixes the issue.

### Expected Behavior

It should not be required to configure 

```hcl
provider "consul" {
  scheme = "https"
}
```

when `CONSUL_HTTP_SSL` is present with a boolean value of `true`.

### Actual Behavior

Configuring the `consul` provider for `scheme = "https"` is required in hcl even if `CONSUL_HTTP_SSL` variable is present with a boolean value of `true`.

### References

* https://github.com/hashicorp/terraform/issues/23688

**Comment by remilapeyre** [comment]
Well, thanks @transferkraM ! This took me far longer than it should have. We were using `"http"` for the default value of the `scheme` attribute and would always override the value we got from `CONSUL_HTTP_SSL`. Defaulting to an empty string is the correct behaviour here.
