### ISSUE TITLE
Applying enterprise consul_license resource results in error

### ISSUE THREAD

**Issue by acornies** [hashicorp/terraform-provider-consul#223]
While applying the `consul_license` enterprise resource, Terraform fails on read of the license schema. However, the license *does* get applied successfully according to Consul. 

From what I can tell, this is due to a mismatched schema for some properties of the license response from Consul.

### Terraform Version
Terraform v0.13.1-dev (testing w/ unrelated salt-masterless changes on https://github.com/hashicorp/terraform/pull/25944)
+ provider registry.terraform.io/hashicorp/consul v2.9.0

### Affected Resource(s)
- consul_license

### Debug Output
```
2020/08/28 11:33:02 [DEBUG] module.consul_ent.consul_license.hce: apply errored, but we're indicating that via the Error pointer rather than returning it: failed to set 'flags': flags.modules: '' expected type 'string', got unconvertible type '[]interface {}'
2020/08/28 11:33:02 [ERROR] eval: *terraform.EvalApplyPost, err: failed to set 'flags': flags.modules: '' expected type 'string', got unconvertible type '[]interface {}'
2020/08/28 11:33:02 [ERROR] eval: *terraform.EvalSequence, err: failed to set 'flags': flags.modules: '' expected type 'string', got unconvertible type '[]interface {}'
2020-08-28T11:33:02.555-0400 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/terraform.tucows.net/tucowsinc/openstackfwaasv2/0.2.0/darwin_amd64/terraform-provider-openstackfwaasv2 pid=89680
2020-08-28T11:33:02.555-0400 [DEBUG] plugin: plugin exited

Error: failed to set 'flags': flags.modules: '' expected type 'string', got unconvertible type '[]interface {}'

  on modules/consul_ent/main.tf line 7, in resource "consul_license" "hce":
   7: resource "consul_license" "hce" {
```

### Expected Behavior
The consul license should be correctly applied and no error is returned from Terraform.

### Actual Behavior
The consul license is applied successfully but Terraform errors.

### Steps to Reproduce
Use a license with the most amount of features for Consul enterprise v1.8.3+ent
1. `terraform apply`

### Important Factoids
Our enterprise Consul license has the highest tier of features.

### References
N/A

**Comment by remilapeyre** [comment]
Thanks for reporting this issue @acornies, I will have a look quickly.
