### ISSUE TITLE
consul_config_entry - Problem with interpolating the name of the data center in the provider

### ISSUE THREAD

**Issue by cageyv** [hashicorp/terraform-provider-consul#231]
### Terraform Version
- Terraform v0.13.4
- provider.consul v.2.10.0

### Affected Resource(s)
- consul_config_entry

### Terraform Configuration Files
- Module config

```hcl
locals {
  dc_name = "dc1"
}

output "dc_name" {
  value = local.dc_name
}
```
- Main config
```hcl
module "my_module" {
  source = "./my_module"
}

provider "consul" {
  address    = "my_consul.example.com:8500"
  datacenter = module.my_module.dc_name
  scheme     = "http"
}

resource "consul_config_entry" "web" {
  name = "web"
  kind = "service-defaults"
  config_json = jsonencode({
    Protocol = "http"
  })
}
```

### Actual Behavior
`Error: Failed to fetch 'web' config entry: &errors.errorString{s:"Unexpected response code: 500 (No path to datacenter)"}`
and new entry in consul config. The record itself was created. An error occurred while trying to execute fetch.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create folder my_module
2. `terraform init` and `terraform apply`

### Important Factoids
If you do not specify the datacenter in the provider, then everything will work
If you specify the datacenter in the provider explicitly, i.e. "dc1" then everything will work

**Comment by remilapeyre** [comment]
Hi @cageyv, I tried to run some tests with a development server (`consul agent -dev`) and could not reproduce the bug.

Are you sure the datacenter was correctly set, for example that there was no extra space as in `"dc1 "`?

**Comment by cageyv** [comment]
Hi @remilapeyre, I have to try it again in my full setup. Maybe I was wrong somewhere between modules or maybe I need to provide more information for reproduce this bug

**Comment by remilapeyre** [comment]
Hi @cageyv, I tried again and could not reproduce your issue. Since it may not be a bug in the Terraform provider but an issue in your configuration I will close the bug for now. Please reopen it if you still have this issue or if you found some way to reproduce it :)
