### ISSUE TITLE
Support namespace and meta in consul_config_entry

### ISSUE THREAD

**Issue by brucec5** [hashicorp/terraform-provider-consul#246]
### Terraform Version
```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/consul v2.11.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
```

### Affected Resource(s)
- consul_config_entry

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    consul = {
      source = "hashicorp/consul"
      version = "2.11.0"
    }
  }
}

provider "consul" {}

resource "consul_namespace" "example_namespace" {
  name = "example"
  description = "Example namespace"
}

resource "consul_config_entry" "test_intentions" {
  kind = "service-intentions"
  name = "destination-service"
  namespace = consul_namespace.example_namespace.name

  config_json = jsonencode({
    Sources = [
      {
        Action = "allow"
        Name = "source-service"
      }
    ]
  })
}
```

### Expected Behavior
Per [the docs](https://www.consul.io/docs/connect/config-entries), it appears that all config entry kinds should support a `namespace` param. In my use-case, it is especially important for [`service-intentions`](https://www.consul.io/docs/connect/config-entries/service-intentions#namespace) to support this, but other config entries should support it too.

Relatedly, it looks like `meta` isn't supported either, despite being a parameter for all config entry kinds.

I'm able to write the same service intention directly via `consul config write`:

```hcl
Kind = "service-intentions"
Name = "destination-service"
Namespace = "example"

Sources = [
  {
    Action = "allow"
    Name = "source-service"
  }
]
```

### Actual Behavior
```
Error: Unsupported argument

  on main.tf line 20, in resource "consul_config_entry" "test_intentions":
  20:   namespace = "example"

An argument named "namespace" is not expected here.
```

### Steps to Reproduce
1. Boot up a consul enterprise agent locally via `consul agent -dev` (consul version 1.9.4+ent)
1. `terraform apply`

### Important Factoids
As mentioned above, I'm using consul 1.9.4+ent

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-232 (PR that added support for service-intentions)

**Comment by fabio-grassi-gbs** [comment]
We are feeling this as a serious gap and hope it is easy as it looks to fix it as we would badly need to create config entry into namespaces.

**Comment by remilapeyre** [comment]
Hi @brucec5 and @fabio-grassi-gbs, sorry for the time it took me to take care of this issue, https://github.com/hashicorp/terraform-provider-consul/pull/256 should do what you are looking for. I will make a new release of the provider shortly.

Here's how you should be able to set a namespace and use the `meta` parameter:

```terraform
resource "consul_namespace" "example_namespace" {
  name = "example"
  description = "Example namespace"
}

resource "consul_config_entry" "test_intentions" {
  kind = "service-intentions"
  name = "destination-service"
  namespace = consul_namespace.example_namespace.name

  config_json = jsonencode({
    Sources = [
      {
        Action = "allow"
        Name = "source-service"
      }
    ]
    Meta = {
        foo = "bar"
    }
  })
}
```

The `consul_config_entry` resource is a bit weird as the schema cannot be expressed nicely with the Terraform SDK v1. I will finally remove the support for Terraform 0.11 and should be able to improve it then.

**Comment by fabio-grassi-gbs** [comment]
Thanks a lot. Ciao ,FG

Da: Rémi Lapeyre ***@***.***>
Inviato: domenica 9 maggio 2021 17:03
A: hashicorp/terraform-provider-consul ***@***.***>
Cc: Grassi Fabio ***@***.***>; Mention ***@***.***>
Oggetto: Re: [hashicorp/terraform-provider-consul] Support namespace and meta in consul_config_entry (#246)


Hi @brucec5<https://github.com/brucec5> and @fabio-grassi-gbs<https://github.com/fabio-grassi-gbs>, sorry for the time it took me to take care of this issue, #256<https://github.com/hashicorp/terraform-provider-consul/pull/256> should do what you are looking for. I will make a new release of the provider shortly.

Here's how you should be able to set a namespace and use the meta parameter:

resource "consul_namespace" "example_namespace" {

  name = "example"

  description = "Example namespace"

}



resource "consul_config_entry" "test_intentions" {

  kind = "service-intentions"

  name = "destination-service"

  namespace = consul_namespace.example_namespace.name



  config_json = jsonencode({

    Sources = [

      {

        Action = "allow"

        Name = "source-service"

      }

    ]

    Meta = {

        foo = "bar"

    }

  })

}

The consul_config_entry resource is a bit weird as the schema cannot be expressed nicely with the Terraform SDK v1. I will finally remove the support for Terraform 0.11 and should be able to improve it then.
