### ISSUE TITLE
consul_services.tags is not implemented 

### ISSUE THREAD

**Issue by nadenf** [hashicorp/terraform-provider-consul#270]
### Terraform Version
1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
consul_services

### Expected Behavior
As per the [documentation](https://registry.terraform.io/providers/hashicorp/consul/latest/docs/data-sources/services), consul_services should have a tags output which is a map of tags -> service names.

### Actual Behavior
As per the [code](https://github.com/hashicorp/terraform-provider-consul/blob/master/consul/data_source_consul_services.go) it hasn't actually been implemented.

**Comment by remilapeyre** [comment]
Hi @nadenf, thanks for reporting this issue, it has been fixed by #274 based on your work.
