### ISSUE TITLE
make bin target does not exist

### ISSUE THREAD

**Issue by nadenf** [hashicorp/terraform-provider-consul#272]
### Terraform Version
1.0.0

### Expected Behavior
As per the [README](https://github.com/hashicorp/terraform-provider-consul) I should be able to run ```make bin``` in order to build this provider.

### Actual Behavior
No such target exists in the [Makefile](https://github.com/hashicorp/terraform-provider-consul/blob/master/GNUmakefile) resulting in the following error:

```
MacBook-Air terraform-provider-consul % make bin
make: *** No rule to make target `bin'.  Stop.
```

**Comment by remilapeyre** [comment]
Hi @nadenf, thanks for reporting this. I updated the build instructions based on the README of https://github.com/hashicorp/terraform-provider-scaffolding to make them closer to the rest of the Terraform providers.
