### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Mongey** [hashicorp/terraform-provider-consul#276]
👋 Hey there, what's the process for getting a new release published.
Looking to get to use #245 😅

**Comment by tkwy-rick** [comment]
Please also: #262

**Comment by remilapeyre** [comment]
Hi, we are in preparing the new release, it should be out shortly.

**Comment by remilapeyre** [comment]
Hi @Mongey, @tkwy-rick sorry for the delay, version 2.13.0 has now been released and you should be able to get it by running `terraform init -upgrade`!
