### ISSUE TITLE
Failed to update service. Request decode failed: json: unknown field "SocketPath"

### ISSUE THREAD

**Issue by sindar225** [hashicorp/terraform-provider-consul#282]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

`Terraform v0.14.11`

### Affected Resource(s)
Please list the resources as a list.

`consul_service`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
```
provider "consul" {
  address = format(
    "%s.%s:%s",
    var.consul_hostname,
    substr(
      data.aws_route53_zone.env.name,
      0,
      length(data.aws_route53_zone.env.name),
    ),
    var.consul_port,
  )
  datacenter = format("%s%s", var.vpcEnvRt53Prefix, var.datacenter_suffix)
  scheme     = "https"
}

locals {
  ec_node_sockets = var.cluster_mode_enabled ? join("", aws_elasticache_replication_group.rg.*.configuration_endpoint_address) : join("", aws_elasticache_replication_group.rg.*.primary_endpoint_address)
  ec_port         = var.ECRG_port
}

resource "consul_node" "ec_node" {
  name    = "ec-${var.env}-${var.ECRG_ServiceName}"
  address = local.ec_node_sockets
  meta = {
    "external-node"  = "true"
    "external-probe" = "false"
  }

  depends_on = [
    aws_elasticache_replication_group.rg,
  ]

}

resource "consul_service" "ec_service" {
  name       = "${var.autodiscovery_name}-${var.ECRG_ServiceName}" ## same, one service to rule them all
  service_id = "${var.autodiscovery_name}-${var.ECRG_ServiceName}"
  node       = consul_node.ec_node.name
  port       = local.ec_port
  tags       = compact(["elasticache", "encrypted", var.ECRG_ServiceName, var.provision])

  # This check is working correctly only with Consul ESM
  check {
    check_id = "service:${var.autodiscovery_name}-${var.ECRG_ServiceName}"
    name     = "EC health check"
    status   = "passing"
    tcp      = "${local.ec_node_sockets}:${local.ec_port}"

    interval                          = "5s"
    timeout                           = "5s"
    deregister_critical_service_after = "0" # keep services in failed state until recovery (eliminates the need of terraform re-apply)
  }

  depends_on = [
    aws_elasticache_replication_group.rg,
  ]
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

`18:02:43  Apply complete! Resources: 0 added, 1 changed, 0 destroyed.`

### Actual Behavior
What actually happened?

```
15:30:16  module.elasticache.consul_service.ec_service: Modifying... [id=elasticache-betradar-gol-trading]
15:30:17  
15:30:17  Error: Failed to update service (dc: 'staging'): Unexpected response code: 400 (Request decode failed: json: unknown field "SocketPath")
15:30:17  
15:30:17    on terra_modules/elasticache/consul-registration.tf line 35, in resource "consul_service" "ec_service":
15:30:17    35: resource "consul_service" "ec_service" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

It works fine if running with `hashicorp/consul v2.12.0`, the problem only happens with the version v.2.13.0

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

**Comment by sindar225** [comment]
It works fine if running with hashicorp/consul v2.12.0, the problem only happens with the version v.2.13.0.

**Comment by blake** [comment]
Hi, @sindar225. Thanks for the bug report. In order to help us troubleshoot this, can you also share the version of Consul that you are using in your environment?

Thanks.

**Comment by sindar225** [comment]
Hi, @blake. It's `Consul 1.9.4`.

**Comment by remilapeyre** [comment]
Hi @sindar225, the latest version of the Terraform provider is usually only compatible with the latest version of Consul as we have are using the Consul SDK which is not always compatible with previous Consul version. Version 2.13.0 is only compatible with Consul 1.10.0 and later. I would like to improve this but it may not be simple to do it.

If you don't need the new features in the provider I think staying on 2.12.0 is probably better for you. If you need some of the bugfixes, I could backport them to make a 2.12.1 release with them.

**Comment by sindar225** [comment]
Hi @remilapeyre, well as for now I need to get terraform pipelines back to working state, new features are optional. Seems like I need to introduce a `version` parameter to every affected provider.

**Comment by remilapeyre** [comment]
> Hi @remilapeyre, well as for now I need to get terraform pipelines back to working state, new features are optional. Seems like I need to introduce a `version` parameter to every affected provider.

Indeed, adding a version like:

```terraform
terraform {
  required_providers {
    consul = {
      source  = "hashicorp/consul"
      version = "2.12.0"
    }
  }
}
```

should get things working again. Also, since Terraform 0.14 there is a dependency lock file that saves the version of each provider used. It seems like it did not helped you here, perhaps you are running Terraform in a CI runner and never saved `.terraform.lock.hcl`? If this is the case I think you can run `terraform init` once for all your projects and commit `.terraform.lock.hcl`, it should make sure that another provider won't be updated without you knowing.

**Comment by sindar225** [comment]
Thank you for clarification and help, @remilapeyre.

**Comment by FernandoMiguel** [comment]
can the changelog pls mention the restriction of newer version of consul?
this should be a major release, not a minor version.
