### ISSUE TITLE
Support for Admin Partitions

### ISSUE THREAD

**Issue by npearce** [hashicorp/terraform-provider-consul#302]
Hi there,

Please add support for Admin Partitions:
https://github.com/hashicorp/terraform-provider-consul/blob/395ecf2cdfdde10b38360c3158ebe67ec6bbfde1/consul/resource_consul_intention.go#L24-L77

### Terraform Version
n/a

### Affected Resource(s)
Please list the resources as a list, for example:
- consul_intention

### Terraform Configuration Files
Need support for this:

```
resource "consul_intention" "public_api_to_product_api" {
  source_name           = "public-api"
  source_namespace      = "default"
  source_partition      = "ecs-dev"
  destination_name      = "product-api"
  destination_namespace = "default"
  destination_partition = "eks-dev"
  action                = "allow"
}
```

### Expected Behavior
Support Admin Partitions for source and destination.

### Actual Behavior
No support for Admin Partitions.

**Comment by remilapeyre** [comment]
Hi @npearce `consul_intention` is deprecated, but `consul_config_entry` has support for Admin partitions in 2.15.1.

Does this fit your needs?

**Comment by npearce** [comment]
Ah, great! I had looked at that, too (pre-1.15.1 release). I'm happy with any working solution.
`consul_config_entry` will do just fine!

**Comment by npearce** [comment]
Resolved
