### ISSUE TITLE
Version 2.15.1 appears to have checksum issues

### ISSUE THREAD

**Issue by askmike1** [hashicorp/terraform-provider-consul#305]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Affecting 0.11.15, 0.12.31, 1.0.11, potentially other versions as well

### Affected Resource(s)
Provider init itself

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Provider should load and work normally

### Actual Behavior
```
Error while installing hashicorp/consul v2.15.1: archive has incorrect
checksum zh:52892673477d9c32b103c14df42e5425e4669dc1b5c37a2083b15ea43093bc7b
(expected
zh:c7faa9a2b11bc45833a3e8e340f22f1ecf01597eaeffa7669234b4549d7dfa85)
```

### Steps to Reproduce
terraform init

### Important Factoids
N/A

### References
N/A

**Comment by allenzahner** [comment]
We have same issue.  Started about an hour ago.

**Comment by bflad** [comment]
The checksums would've changed if the repository contents changed between 2.15.1 release attempts. In general, it is best to cut a new release in that scenario. I have submitted CDN purge requests for releases.hashicorp.com/terraform-provider-consul/2.15.1/* to try and alleviate the issue, however a better fix may be to just cut a "clean" 2.15.2.

**Comment by mazjindeel-code42** [comment]
Your CDN purge request seems to has fixed it for version 2.15.1. Thank you for the quick turnaround!

**Comment by askmike1** [comment]
Can confirm as well it is working again

**Comment by remilapeyre** [comment]
Hi, sorry about this. The release process changed and the first try at getting 2.15.1. Failed so I had to try it again and it apparently produced binaries with a different checksum.

@bflad should I cut a fresh 2.15.2 release to make sure all no one else relies on 2.15.1?

**Comment by remilapeyre** [comment]
Hi @askmike1, thanks for reporting this issue. Everything has been fixed now :)
