### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dolevf** [hashicorp/terraform-provider-consul#339]
Hi,

Wondering if there's any plan to release a new version any time soon? asking because a few CVEs were resolved by dependabot last month (mastermind go utils repository in go.mod) and wanted to know when we can get these baked into the next release.

Thank you!

**Comment by remilapeyre** [comment]
Hi @dolevf, a new release should go out in a couple of days

**Comment by dolevf** [comment]
Thank you!

**Comment by simonctrlz** [comment]
How did that go?

**Comment by remilapeyre** [comment]
Hello @dolevf, @simonctrlz, the new version has been released. Sorry about the delay.
