### ISSUE TITLE
consul_service check_id isn't optional as documented in registry

### ISSUE THREAD

**Issue by const-tmp** [hashicorp/terraform-provider-consul#350]
### Terraform Version
terraform version
Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/consul v2.17.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/nomad v1.4.20
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/hashicorp/vault v3.18.0
### Affected Resource(s)
Please list the resources as a list, for example:
- consul_service

### Terraform Configuration Files
```hcl
resource "consul_service" "esm-service" {
  for_each = var.esm-services
  name = each.key
  node = consul_node.esm-node[each.value.node].name

  check {
    interval = "15s"
    name     = "${each.key} http check"
    timeout  = "1s"
    http     = "https://${consul_node.esm-node[each.value.node].address}"
  }
}
```
### Expected Behavior
What should have happened?
Resource is created with check_id equal to name as documented [here](https://registry.terraform.io/providers/hashicorp/consul/latest/docs/resources/service#check_id)

### Actual Behavior
What actually happened?
```
╷
│ Error: Missing required argument
│
│   on consul-esm.tf line 47, in resource "consul_service" "esm-service":
│   47:   check {
│
│ The argument "check_id" is required, but no definition was found.
╵
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by remilapeyre** [comment]
Hello @const-tmp, thanks for reporting this! https://github.com/hashicorp/terraform-provider-consul/pull/352 will update the documentation.
