### ISSUE TITLE
`config_entry` should ignore `Status` key when determining diffs

### ISSUE THREAD

**Issue by sorenisanerd** [hashicorp/terraform-provider-consul#359]
The docs for `consul_config_entry` has a warning:

    Because the schema in a consul_config_entry resource can very widely
    between the various configuration entry kinds, it is necessary to
    explicitly define every attribute to avoid Terraform reporting a diff
    on the resource.

I can handle littering my configuration with a bunch of `null`s and `[]`s, but having to embed the contents of the `Status` key of my `api-gateway`, `http-route`, and `tcp-route` in my Terraform is ridiculous.

Because it's a JSON string, I can't use `lifecycle.ignore_changes` to work around it either.

**Comment by remilapeyre** [comment]
Hi @sorenisanerd, we are working on adding additional resources for the config entries that will alleviate this issues. `consul_config_entry` should still be fixed thought. I will work on this.
